/**
 * @module converter/emoji
 * @description Emoji ID 到字符的映射
 * 参考: https://open.feishu.cn/document/docs/docs/data-structure/emoji
 */

const emojiMap: Record<string, string> = {
  // 笑脸与人
  smile: '😄',
  laughing: '😆',
  blush: '😊',
  smiley: '😃',
  relaxed: '☺️',
  smirk: '😏',
  heart_eyes: '😍',
  kissing_heart: '😘',
  kissing_closed_eyes: '😚',
  flushed: '😳',
  relieved: '😌',
  satisfied: '😆',
  grin: '😁',
  wink: '😉',
  stuck_out_tongue_winking_eye: '😜',
  stuck_out_tongue_closed_eyes: '😝',
  grinning: '😀',
  kissing: '😗',
  kissing_smiling_eyes: '😙',
  stuck_out_tongue: '😛',
  sleeping: '😴',
  worried: '😟',
  frowning: '😦',
  anguished: '😧',
  open_mouth: '😮',
  grimacing: '😬',
  confused: '😕',
  hushed: '😯',
  expressionless: '😑',
  unamused: '😒',
  sweat_smile: '😅',
  sweat: '😓',
  disappointed_relieved: '😥',
  weary: '😩',
  pensive: '😔',
  disappointed: '😞',
  confounded: '😖',
  fearful: '😨',
  cold_sweat: '😰',
  persevere: '😣',
  cry: '😢',
  sob: '😭',
  joy: '😂',
  astonished: '😲',
  scream: '😱',
  tired_face: '😫',
  angry: '😠',
  rage: '😡',
  triumph: '😤',
  sleepy: '😪',
  yum: '😋',
  mask: '😷',
  sunglasses: '😎',
  dizzy_face: '😵',
  imp: '👿',
  smiling_imp: '😈',
  neutral_face: '😐',
  no_mouth: '😶',
  innocent: '😇',
  alien: '👽',
  thinking: '🤔',
  thinking_face: '🤔',
  rolling_eyes: '🙄',
  zipper_mouth_face: '🤐',
  nerd_face: '🤓',

  // 手势
  thumbsup: '👍',
  thumbsdown: '👎',
  ok_hand: '👌',
  punch: '👊',
  fist: '✊',
  v: '✌️',
  wave: '👋',
  hand: '✋',
  raised_hand: '✋',
  open_hands: '👐',
  point_up: '☝️',
  point_down: '👇',
  point_left: '👈',
  point_right: '👉',
  raised_hands: '🙌',
  pray: '🙏',
  clap: '👏',
  muscle: '💪',
  writing_hand: '✍️',

  // 心形
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  heart: '❤️',
  broken_heart: '💔',
  heartbeat: '💓',
  heartpulse: '💗',
  two_hearts: '💕',
  sparkling_heart: '💖',
  revolving_hearts: '💞',
  cupid: '💘',

  // 自然
  sunny: '☀️',
  umbrella: '☂️',
  cloud: '☁️',
  snowflake: '❄️',
  snowman: '⛄',
  zap: '⚡',
  cyclone: '🌀',
  foggy: '🌁',
  rainbow: '🌈',
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  fire: '🔥',
  boom: '💥',

  // 物品
  bulb: '💡',
  book: '📖',
  bookmark: '🔖',
  pencil: '📝',
  pencil2: '✏️',
  pushpin: '📌',
  paperclip: '📎',
  triangular_ruler: '📐',
  straight_ruler: '📏',
  scissors: '✂️',
  computer: '💻',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  bell: '🔔',
  link: '🔗',
  wrench: '🔧',
  hammer: '🔨',
  trophy: '🏆',
  medal_sports: '🏅',
  rocket: '🚀',
  dart: '🎯',
  gem: '💎',
  gift: '🎁',
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',

  // 标志
  checkered_flag: '🏁',
  white_check_mark: '✅',
  ballot_box_with_check: '☑️',
  heavy_check_mark: '✔️',
  x: '❌',
  heavy_multiplication_x: '✖️',
  exclamation: '❗',
  question: '❓',
  grey_exclamation: '❕',
  grey_question: '❔',
  warning: '⚠️',
  bangbang: '‼️',
  interrobang: '⁉️',
  '100': '💯',
  recycle: '♻️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  ok: '🆗',
  plus: '➕',
  minus: '➖',
  arrow_right: '➡️',
  arrow_left: '⬅️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',

  // 钟表
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  watch: '⌚',
  alarm_clock: '⏰',
  clock1: '🕐',

  // 食物
  coffee: '☕',
  hamburger: '🍔',
  pizza: '🍕',
  beer: '🍺',
  wine_glass: '🍷',

  // 动物
  dog: '🐶',
  cat: '🐱',
  mouse: '🐭',
  rabbit: '🐰',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  bug: '🐛',
  bee: '🐝',
  butterfly: '🦋',
  snail: '🐌',
  turtle: '🐢',
  snake: '🐍',
  whale: '🐳',
  dolphin: '🐬',
  fish: '🐟',
  octopus: '🐙',

  // 植物
  cherry_blossom: '🌸',
  rose: '🌹',
  sunflower: '🌻',
  herb: '🌿',
  four_leaf_clover: '🍀',
  maple_leaf: '🍁',
  fallen_leaf: '🍂',
  cactus: '🌵',
  palm_tree: '🌴',
  evergreen_tree: '🌲',
  deciduous_tree: '🌳',
  seedling: '🌱',

  // 其他常用
  DONE: '✅',
  LOVE: '❤️',
  THUMBSUP: '👍',
  FIRE: '🔥',
  ROCKET: '🚀',
  STAR: '⭐',
  WARNING: '⚠️',
  BULB: '💡',
  MEMO: '📝',
  EYES: '👀',
  eyes: '👀',
  memo: '📝',
  speech_balloon: '💬',
  thought_balloon: '💭',
  information_source: 'ℹ️',
  abc: '🔤',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  heavy_dollar_sign: '💲',
};

/**
 * 根据 emoji_id 获取对应的 emoji 字符
 * 如果找不到映射，返回 emoji_id 本身作为文本
 */
export function getEmojiChar(emojiId: string): string {
  if (!emojiId) return '';
  return emojiMap[emojiId] || emojiMap[emojiId.toLowerCase()] || emojiId;
}
